name: Django CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install poetry
          python -m poetry install
          python -m poetry env use python

      - name: Create Django project
        run: |
          python -m django startproject project
          cp -r drf_hf_hub project/drf_hf_hub

      - name: Configure project settings
        run: |
          echo "INSTALLED_APPS += ['drf_hf_hub', 'drf_redesign', 'rest_framework']" >> project/settings.py
          echo "from django.urls import include" >> project/urls.py
          echo "urlpatterns += [path('', include('drf_hf_hub.urls')), path('', include('rest_framework.urls'))]" >> project/urls.py

      - name: Run check and tests
        run: |
          cd project
          python manage.py check
          python manage.py test
